workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - keystore_reference  # A configurer plus tard
    scripts:
      - name: Get Flutter packages
        script: flutter packages get
      - name: Build APK
        script: flutter build apk --release
      - name: Build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - fleyrissoux@inf-ia.com
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      email:
        recipients:
          - fleyrissoux@inf-ia.com
        notify:
          success: true
          failure: true

  # Windows build via GitHub Actions (Codemagic ne supporte pas Windows)
